### ISSUE TITLE
Registration functionality

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-turnstile#14]
The below image's "submit" should find the user in the database and add a Registration row in the database. Realize that there currently is no such thing as a Registration.

- [x] Add Registered table

Keep in mind that when you create this table, it should have a relation to a Student. I want to be able to do `prisma.student.findAll({ include: { registrations: true } })`

- [ ] On submit, add a row to that registration table.

![Image](https://user-images.githubusercontent.com/45398785/220120653-d3151405-e70e-4507-a09a-b002b0bf8e69.png)

**Comment by kcouv** [comment]
Registration model in the db has a typo: currently it is spelled "Registeration"

**Comment by kcouv** [comment]
How do we know which event the student is being registered for? Having trouble finding that

**Comment by SpBills** [comment]
```
student > registration < event
                       |> checkin
