### ISSUE TITLE
Event Select

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-turnstile#21]
We need to be able to select what event we are "purchasing" for.

I don't know exactly how we want to do this...

Here are some options:
1. we set in the database an "active" event. just a flag on the event, and just make sure only one is ever true.
2. have a "select event" page that then sets a session variable.

2 is probably the more proper one.

**Comment by SebastianNeiswanger** [comment]
I plan to go with the second method as I want there to be the opportunity for overlapping event times.

**Comment by SebastianNeiswanger** [comment]
https://www.andreadiotallevi.com/blog/how-to-implement-client-side-redirects-in-next-js
for redirecting in client components
